# Generated by Django 2.2.8 on 2020-01-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200123_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikull',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
