# Generated by Django 2.2.8 on 2020-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200314_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikull',
            name='categ',
            field=models.IntegerField(choices=[(1, 'Politike'), (2, 'Aktualitet'), (3, 'Sport'), (4, 'Lifestyle'), (5, 'Rajoni'), (6, 'Bota'), (7, 'Teknologji'), (8, 'Kuriozitet'), (9, 'Kulture'), (10, 'Kronike'), (11, 'Te Tjera')], default=11),
        ),
    ]
