# Generated by Django 2.2.8 on 2020-02-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrossWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('live_Url', models.TextField(default=' ')),
                ('des', models.TextField(default=' ')),
                ('code_url', models.TextField(default=' ')),
                ('background', models.CharField(max_length=250)),
                ('pos', models.IntegerField(default=4)),
            ],
        ),
    ]
