# Generated by Django 2.2.8 on 2020-02-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrossWord',
            new_name='Extra',
        ),
    ]
