# Generated by Django 2.2.8 on 2020-01-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('length', models.IntegerField(default=35)),
                ('popularity', models.IntegerField(default=1)),
                ('used', models.IntegerField(default=1)),
                ('solved', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(max_length=255)),
                ('ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cw.Ans')),
            ],
        ),
    ]
