# Generated by Django 2.2.8 on 2020-02-01 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cw', '0002_auto_20200130_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.IntegerField(default=0)),
                ('j', models.IntegerField(default=0)),
                ('orientation', models.CharField(max_length=1)),
                ('word', models.CharField(max_length=30)),
                ('crosword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cw.CrossWord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
