# Generated by Django 2.2.8 on 2020-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw', '0003_crossword_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hint',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
